trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy to Azure'
  steps:
  - task: Docker@2
    displayName: 'Azure Container Registry Login'
    inputs:
      command: 'login'
      containerRegistry: 'todolistproject.azurecr.io'  # Use the full URL of your ACR
      
  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      command: 'buildAndPush'
      containerRegistry: 'todolistproject.azurecr.io'  # Use the full URL of your ACR
      repository: 'saiid21/todolist-cicd'
      dockerfile: '**/Dockerfile'
      tags: 'latest'
      
  - task: AzureCLI@2
    displayName: 'Deploy to Azure App Service'
    inputs:
      azureSubscription: '51fbbda4-8f8b-463f-8cf8-1a3a3ef8d067'  # Service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp config container set --name todoproject --resource-group project --docker-custom-image-name https://todolistproject.azurecr.io/saiid21/todolist-cicd:latest
