trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'YourAzureContainerRegistry' # Name of your Azure Container Registry service connection
    repository: 'yourrepository' # Name of your repository in ACR
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
